plugins {
	id 'java'
}

repositories {
	mavenLocal()
	maven {
		url = 'https://repo.runelite.net'
	}
	mavenCentral()
}

def runeLiteVersion = 'latest.release'

dependencies {
	compileOnly "net.runelite:client:${runeLiteVersion}"

	compileOnly 'org.projectlombok:lombok:1.18.44'
	annotationProcessor 'org.projectlombok:lombok:1.18.44'

	testImplementation 'junit:junit:4.13.2'
	testImplementation "net.runelite:client:${runeLiteVersion}"
}

group = 'com.tcglocked'
version = '1.2.3'

java {
	sourceCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}
